HODS-105 | Add endpoints, schemas, and examples to preliminary docs
hmrc/organisations-matching-api pull request #15
Opened 2021-04-29 10:23 UTC by Luka-Abey

2021-04-29 12:15 UTC, parkeradam requested changes
Also seems to be mising Correlation Id Malformed erros and stuff, all sits in the sandbox-data section of the individuals repos.

2021-04-29 13:52 UTC, parkeradam approved these changes

2021-04-29 15:11 UTC, ajchilts requested changes

2021-05-05 12:38 UTC, ajchilts approved these changes

2021-05-05 13:14 UTC, parkeradam requested changes

2021-05-05 13:14 UTC, parkeradam commented on resources/public/api/conf/1.0/application.raml
> +                type: !include schemas/paye-details-response.json
thi payload seems wrong, running locally shows "taxpayer type and taxpayer name" whereas matrix shows employerName.

2021-05-05 13:14 UTC, parkeradam commented on resources/public/api/conf/1.0/schemas/sautr-details-response.json
> +        "addressLine3": {
Missing description, check individuals as address descriptions have been solidified in there. Check addresse on all schemas in here please.

2021-05-05 13:14 UTC, parkeradam commented on resources/public/api/conf/1.0/application.raml
>          headers:
Missing correlationId Header, should be on all endpoints.

2021-05-05 15:01 UTC, parkeradam approved these changes

2021-05-06 13:35 UTC, ajchilts approved these changes

2021-05-06 13:35 UTC, merged