Update API documentation for scope handler pattern based authorisation
hmrc/organisations-matching-api pull request #43
Opened 2021-07-23 11:42 UTC by ajchilts

2021-07-27 08:53 UTC, owen-opencast requested changes

2021-07-27 08:53 UTC, owen-opencast commented on resources/public/api/conf/1.0/docs/post-corporation-tax-description.md
> +<p>Details include: company registration number (CRN), employer name, and address. On a successful match, a matchId is returned.</p>
Move "On a successful match..." to the third paragraph, to match the SA description?

2021-07-28 07:44 UTC, Luka-Abey approved these changes

2021-07-28 11:24 UTC, owen-opencast approved these changes

2021-07-28 12:57 UTC, Luka-Abey requested changes
couple small bits on re-review

2021-07-28 12:57 UTC, Luka-Abey commented on resources/public/api/conf/1.0/application.raml
> +  /matching/self-assessment:
matching is duplicated in the full path 
```suggestion
  /self-assessment:
```

2021-07-28 12:57 UTC, Luka-Abey commented on resources/public/api/conf/1.0/application.raml
> +        is: [headers.acceptHeader, headers.contentHeader]
should not include content-type for get endpoint 
```suggestion
        is: [headers.acceptHeader]
```

2021-07-28 13:16 UTC, Luka-Abey approved these changes

2021-07-28 15:06 UTC, merged