HODS-appIdFix | Added convert method to push appropriate headercarriers
hmrc/organisations-matching-api pull request #54
Opened 2021-08-10 09:26 UTC by matthewharris1

2021-08-10 09:58 UTC, owen-opencast requested changes

2021-08-10 09:58 UTC, owen-opencast commented on app/uk/gov/hmrc/organisationsmatchingapi/connectors/OrganisationsMatchingConnector.scala
> +    val appId = getValue("X-Application-ID")
Using this string constant twice - I'd define them in a list (requiredHeaders or some such), and have getValue return the tuple of (headerName, headerValue) - headerConvert would then just map the sequence of required Headers by calling getValue and return.

2021-08-11 09:25 UTC, Luka-Abey approved these changes

2021-08-11 09:29 UTC, owen-opencast approved these changes

2021-08-13 13:32 UTC, merged