HODS-337 | Changed documentation and areas in which code differs from…
hmrc/organisations-matching-api pull request #62
Opened 2021-09-02 09:49 UTC by matthewharris1

… docs

2021-09-02 10:49 UTC, parkeradam requested changes
line 13 on spreadsheet is not complete. 
Line 20 on the spreadsheet is not complete.
Line 24 of the spreadsheet is not complete.
Line 26 of spreadsheet in not complete.

It also a bit hard to figure out if the actual responses do, I'll run this and hit endpoints to check response titles once the documentation has been fixed.

2021-09-02 10:49 UTC, parkeradam commented on resources/public/api/conf/1.0/examples/sautr-details-response-example.json
> +    "postcode": "t"
```suggestion
    "postcode": "AB12 3CD"
```

2021-09-02 14:12 UTC, parkeradam approved these changes

2021-09-02 15:11 UTC, Luka-Abey commented on resources/public/api/conf/1.0/examples/corporation-tax-matching-response-example.json
> +      "title": "Get links to Corporation Tax and number of employee details for a matched organisation"
```suggestion
      "title": "Get links to Corporation Tax and number of employees details for a matched organisation"
```

2021-09-02 15:11 UTC, Luka-Abey commented on resources/public/api/conf/1.0/schemas/corporation-tax-matching-response.json
> +              "description": "Get links to Corporation Tax and number of employee details for a matched organisation"
```suggestion
              "description": "Get links to Corporation Tax and number of employees details for a matched organisation"
```

2021-09-02 15:12 UTC, Luka-Abey commented on test/component/uk/gov/hmrc/organisationsmatchingapi/controllers/MatchingControllerSpec.scala
> +           |      "title" : "Get links to Corporation Tax and number of employee details for a matched organisation"
```suggestion
           |      "title" : "Get links to Corporation Tax and number of employees details for a matched organisation"
```

2021-09-03 07:20 UTC, Luka-Abey approved these changes

2021-09-03 12:55 UTC, merged